/**
 * Script to update all facts with 5 quality wrong answers each.
 * Run: node scripts/apply_answers.js
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Updates: { id, wrong: [5 strings], correct: string (optional, only if shortening needed) }
const UPDATES = [
  { id: 1, wrong: ["Elles prennent la forme du trou","Elles deviennent carrées","Elles explosent plus vite","Elles se divisent en deux","Elles sont plus fragiles"] },
  { id: 2, wrong: ["Il envoyait une carte de condoléances","Il appelait la police anonymement","Il publiait un poème sur Facebook","Il commandait une pizza après","Il envoyait des fleurs aux familles"] },
  { id: 3, wrong: ["Elle court à reculons comme un crabe","Elle tisse des toiles en entonnoir","Elle marche sur l'eau sans couler","Elle mord deux fois plus fort","Elle a des pinces comme un crabe"] },
  { id: 4, wrong: ["Un virus a bloqué tous les GPS","Une voiture volante a été testée","La ville a interdit les voitures","Un robot a dirigé la circulation","Un bus automatique a déraillé"] },
  { id: 5, wrong: ["Des rondelles de bois sculpté","Des pierres plates taillées","Des morceaux de glace taillés","Des pommes de pin gelées","Des boules de neige durcie"] },
  { id: 6, wrong: ["Un jet militaire hypersonique","Une balle de fusil de sniper","La fusée la plus rapide de la NASA","Une Ferrari à pleine vitesse","Un missile balistique"] },
  { id: 7, wrong: ["Rivière souterraine dans la Bible","Technique de calligraphie orientale","Transe mystique dans le soufisme","Sorte de petit arbre sacré","Petite divinité grecque"] },
  { id: 8, wrong: ["Inventé par un dentiste daltonien","D'après la couleur des premiers câbles","Un nom choisi au hasard par loterie","Acronyme d'un protocole anglais","Inspiré d'une baie nordique danoise"] },
  { id: 9, wrong: ["Elle peint uniquement avec ses pieds","Elle crée de la musique avec sa peinture","Elle mélange musique et parfums rares","Elle vend ses peintures en tant que sons","Elle dessine à l'aveugle en rythme"] },
  { id: 10, wrong: ["La sève de coco cristallisée","Une variété d'herbe médicinale","Un lichen comestible des forêts","Une infusion de racine amère","Un type d'algue verte aquatique"] },
  { id: 11, wrong: ["La peur de l'altitude","La peur des tunnels","La peur de traverser la rue","La peur des rivières profondes","La peur de l'eau courante"] },
  { id: 12, wrong: ["Jackie Chan","Sylvester Stallone","Bruce Willis","Arnold Schwarzenegger","Chuck Norris"] },
  { id: 13, wrong: ["Il a plu des poissons rouges","Il a plu des méduses vivantes","Il a plu des pommes et des poires","Il a plu des cailloux de sel","Il a plu des fourmis ailées"] },
  { id: 14, wrong: ["Du graphite et de la pression","De la cendre volcanique","Du carbone et de l'azote","Des déchets industriels","Du sel gemme compressé"] },
  { id: 15, wrong: ["Il a tiré un avion avec son oreille","Il a poussé une voiture avec sa langue","Il a porté 5 personnes sur sa tête","Il a mangé 50 piments en 1 minute","Il a fait 1000 pompes en 30 minutes"] },
  { id: 16, wrong: ["Un désir compulsif de boire du sang","Une allergie sévère aux protéines","Une sensibilité extrême à la lumière","Un manque de pigments dans la peau","Une maladie qui donne l'air d'un mort"] },
  { id: 17, wrong: ["La peur d'être observé par des caméras","La peur de son reflet dans l'eau","La peur d'avoir les yeux ouverts","La peur des photos de soi","La peur de vieillir en se voyant"] },
  { id: 18, wrong: ["Interdit de klaxonner après 22h","Interdit de manger au volant","Interdit de conduire nu","Interdit de stationner devant une église","Interdit de conduire en sandales"] },
  { id: 19, wrong: ["Une caisse de téléphones portables","Un filet de pêche entier","Un container de marchandises","Un kayak avec son équipage","Un plongeur avec sa bouteille"] },
  { id: 20, wrong: ["Interdit de nourrir les élans en ville","Interdit de faire des selfies avec un élan","Interdit de chasser les élans le dimanche","Interdit d'attacher un élan à son véhicule","Interdit de vendre les bois d'élan"] },
  { id: 21, wrong: ["Le cœur en plein effort physique","Les deux reins ensemble","Les muscles d'un sportif en action","Le foie après un repas copieux","Les poumons lors d'une respiration"] },
  { id: 22, wrong: ["Elle a donné naissance à des quadruplés","Elle avait deux groupes sanguins à la fois","Elle a accouché de jumeaux en dormant","Elle avait deux utérus fonctionnels","Elle a eu des bébés à 60 ans naturellement"] },
  { id: 23, wrong: ["Le ver de terre commun","Le poisson-clown","Le poulpe de l'océan Pacifique","La pieuvre commune des mers","Le bernard-l'ermite géant"] },
  { id: 24, wrong: ["Qui mange avec excès et sans hygiène","Qui souffre de maux d'estomac chroniques","Qui a mauvaise mine mais bonne santé","Qui évite les maladies en s'isolant","Qui est allergique à tout médicament"] },
  { id: 25, wrong: ["Il peut changer de couleur en 1 seconde","Il voit les couleurs comme les humains","Il peut voir dans l'obscurité totale","Il peut zoomer sur sa proie à distance","Il voit trois fois mieux que l'aigle"] },
  { id: 26, wrong: ["La disparition d'un lac entier","Le vol d'une colline entière","Le vol de sable d'une île","La disparition d'une forêt","Le vol d'une cascade entière"] },
  { id: 27, wrong: ["Le pingouin","L'éléphant","Le cheval","Le chien","Le mouton"] },
  { id: 28, wrong: ["La peur des enfants bruyants","La peur des clowns et des marionnettes","La peur des jouets qui se déplacent","La peur des bébés","La peur des masques de carnaval"] },
  { id: 29, wrong: ["Le cercueil était trop petit pour lui","Sa couronne a roulé jusqu'au public","Les assistants se sont battus entre eux","Son cercueil a pris feu","Le cheval funèbre s'est emballé"] },
  { id: 30, wrong: ["Elle perçoit les couleurs par le toucher","Elle distingue les formes par l'ouïe","Elle récupère la vue sous hypnose","Elle voit uniquement en noir et blanc","Elle voit pendant ses crises"], correct: "Elle voit avec certaines personnalités" },
  { id: 31, wrong: ["La peur des numéros inconnus","La peur des téléphones qui sonnent","La peur d'être suivi par son téléphone","La peur des notifications","La peur de perdre ses données"] },
  { id: 32, wrong: ["Elles changent de taille selon les films","Elles sont plus grandes que la tête","Elles bougent selon les émotions","Elles sont rondes depuis l'origine","Elles pointent toujours vers le haut"] },
  { id: 33, wrong: ["La peur des hippopotames","La peur de ne pas trouver ses mots","La peur de mal prononcer les mots","La peur des textes trop longs","La peur de parler en public"] },
  { id: 34, wrong: ["Interdit de chasser en ski","Interdit de chasser sans casque","Interdit de chasser le dimanche soir","Interdit de chasser avec un arc","Interdit de chasser avec un téléphone"] },
  { id: 35, wrong: ["Il guérit toutes les blessures","Il est produit sans les abeilles","Il est plus sucré que le sucre","Il durcit si on y ajoute de l'eau","Il se conserve mieux que le vin"] },
  { id: 36, wrong: ["Envie de dormir en plein repas","Envie irrésistible de s'allonger","Addiction aux somnifères","Peur de sortir de sa zone de confort","Tendance à tomber souvent de son lit"] },
  { id: 37, wrong: ["Un poulpe vivant","Une chenille électrique","Une anguille électrique","Un crapaud sonore","Un serpent à sonnette"] },
  { id: 38, wrong: ["La peur des perruques","La peur de perdre ses cheveux","La peur des hommes aux crânes rasés","La peur d'avoir les cheveux blancs","La peur des crânes en général"] },
  { id: 39, wrong: ["Des verres de lunettes broyés","Du cristal de roche compressé","De l'or en feuille ultra fine","Des fibres de carbone optiques","Du plastique transparent spécial"] },
  { id: 40, wrong: ["Il a couru un marathon pieds nus","Il a nagé 200 km dans la mer","Il a couru 300 km sous la pluie","Il a fait 40 marathons en 40 jours","Il a escaladé l'Everest deux fois"] },
  { id: 41, wrong: ["Il a été momifié et exposé en galerie","Son portrait a été revendu à Hollywood","Il a été enterré avec ses œuvres d'art","Son costume a été porté par un acteur","Sa silhouette a inspiré un film célèbre"] },
  { id: 42, wrong: ["La peur des plumes en général","La peur des œufs","La peur des basses-cours","La peur du bruit des coqs","La peur des volailles"] },
  { id: 43, wrong: ["Un logiciel d'analyse moléculaire","Un vaccin contre une maladie rare","Une réaction chimique inédite","Un cristal inconnu en laboratoire","Un élément du tableau périodique"] },
  { id: 44, wrong: ["L'île de Malte entière","Monaco pour une journée","Une île privée aux Maldives","Le Palais de Versailles","L'archipel des Bermudes"] },
  { id: 45, wrong: ["Le plus grand nombre de buts en finale","Le match le plus long de l'histoire","Le premier penalty contre la VAR","Le stade le plus plein de l'histoire","Le plus de cartons rouges en un match"] },
  { id: 46, wrong: ["Elle grave avec des acides","Elle dessine avec des bactéries","Elle sculpte avec de l'ADN","Elle peint avec son propre sang","Elle tisse avec des moisissures"] },
  { id: 47, wrong: ["L'extinction des dinosaures à cette heure","L'invention de l'écriture","Le début de l'ère industrielle","L'arrivée des Romains en Europe","La naissance des premières villes"] },
  { id: 48, wrong: ["Elle a survécu à un éclair en plein salon","Un satellite lui a atterri sur la maison","Elle a survécu à une explosion de gaz","Un avion lui a atterri sur sa voiture","Elle a survécu à deux séismes"] },
  { id: 49, wrong: ["Plante qui fleurit la nuit","Animal actif uniquement la nuit","Phase lunaire de 24 heures","Période de transition jour/nuit","Cycle de sommeil profond de l'humain"] },
  { id: 50, wrong: ["Le carpaccio de dauphin","Le foie gras de perroquet","Le consommé d'éléphant","Le blanc de baleine grillé","Le steak de rhinocéros rôti"] },
  { id: 51, wrong: ["Ils pensent être des moutons","Ils pensent être des chevaux","Ils mangent de l'herbe","Ils beuglent comme des bœufs","Ils refusent de parler aux humains"] },
  { id: 52, wrong: ["Il a été écrit avec les pieds des deux auteurs","Il a été écrit avec un pinceau japonais","Il a été écrit en une seule nuit sans s'arrêter","Il a été écrit à l'envers","Il a été dicté par un perroquet"] },
  { id: 53, wrong: ["Il a commandé 50 pizzas pour ses amis","Il a fugué vers Disneyland Paris","Il a acheté tout le stock d'une boutique","Il a essayé de conduire un camion","Il a construit une cabane sur le toit"], correct: "Il a pris la voiture pour acheter une Lamborghini" },
  { id: 54, wrong: ["Un festival de sauce tomate géant","Une course de tomates roulantes","Un championnat de lancer de tomates","Un concours de soupe froide","Un marché de tomates centenaires"] },
  { id: 55, wrong: ["La fraise","La pomme de terre","Le riz","Le maïs","L'avocat"] },
  { id: 56, wrong: ["Elle avale ses pattes de devant","Elle retient ses proies sous l'eau","Elle aspire sa proie d'un coup","Elle paralyse sa proie avant d'avaler","Elle digère ses proies en marchant"] },
  { id: 57, wrong: ["Interdit de fumer à l'intérieur","Interdit de chanter en buvant","Interdit de se bagarrer avec un verre","Interdit d'amener son chien","Interdit de téléphoner au comptoir"] },
  { id: 58, wrong: ["Un ver dans ses globes oculaires","Un parasite qui ronge le nez","Un champignon dans sa cornée","Une larve dans sa peau","Un insecte logé dans son oreille"] },
  { id: 59, wrong: ["Il a empilé cinq raisins","Il a fait tenir 10 billes sur une pièce","Il a équilibré 3 couteaux sur un doigt","Il a empilé 12 pièces en spirale","Il a fait tenir un œuf debout"] },
  { id: 60, wrong: ["En buvant des herbes médicinales","En faisant une thérapie par le sport","En prenant un médicament expérimental","En pratiquant l'hypnose profonde","En suivant un régime strict"] },
  { id: 61, wrong: ["Une chute de 5 km en parachute défectueux","Une plongée à 800 m de profondeur","Une chute de 3 km depuis un avion","Une chute depuis un pont de 200 m","Une chute en rappel de 2 km"] },
  { id: 62, wrong: ["Il a gravi l'Everest les yeux bandés","Il a escaladé en hiver sans équipement","Il a battu le record de vitesse mondial","Il a grimpé en courant","Il a escaladé deux sommets en un jour"] },
  { id: 63, wrong: ["Des chiens renifleurs de bombes","Des robots sous-marins pilotés","Des chats espions miniaturisés","Des corbeaux dressés au combat","Des pigeons voyageurs armés"] },
  { id: 64, wrong: ["La peur des cercueils","La peur de la mort","La peur du noir total","La peur d'être seul dans la nuit","La peur des cimetières"] },
  { id: 65, wrong: ["Un troupeau de moutons","12 singes","3 chèvres naines","Un chien de race rare","8 lapins blancs"] },
  { id: 66, wrong: ["Pour le faire parler d'un meurtre","Pour lui voler ses plumes dorées","Pour le bénir avant la saison","Pour lui interdire de chanter la nuit","Pour le soigner de la grippe"] },
  { id: 67, wrong: ["Un filet de sécurité tendu","Le toit d'une voiture","La cime d'un arbre","L'auvent d'un magasin","Un balcon avec des coussins"] },
  { id: 68, wrong: ["La peur des grandes tablées","La peur des repas trop épicés","La peur d'avaler de travers","La peur de manger en public","La peur des restaurants bondés"] },
  { id: 69, wrong: ["Petit insecte nocturne au vol silencieux","Plante grimpante à fleurs rouges","Tourbillon d'eau sous-marine","Tache de lumière sur un mur","Vibration grave dans un instrument"] },
  { id: 70, wrong: ["Résidu inutile ou encombrant","Langue morte jamais traduite","Erreur grammaticale codifiée","Terme utilisé dans une seule région"] , correct: "Mot ou expression n'apparaissant qu'une fois" },
  { id: 71, wrong: ["1874","1906","1887","1895"] },
  { id: 72, wrong: ["Elle a vécu 20 ans sans jamais manger","Elle a prédit sa propre mort à l'heure","Elle a dormi 40 jours sans se réveiller","Elle voyait à travers les murs","Elle entendait les pensées des autres"] },
  { id: 73, wrong: ["Il a nagé 200 km avec des chaînes","Il a traversé un lac gelé en apnée","Il a nagé à reculons pendant 5h","Il a fait 100 longueurs sans respirer","Il a nagé les yeux bandés sous l'eau"] },
  { id: 74, wrong: ["Un immeuble entier a été soufflé","Des voitures ont volé à 500 m","Le nuage a atteint la stratosphère","Des milliers de personnes ont été blessées","Une ville entière a été évacuée"] },
  { id: 75, wrong: ["Il a atterri sur le toit d'un immeuble","Un passager a piloté en urgence","Il a flotté grâce au gilet de sauvetage","Il s'est accroché à une aile d'avion","La soute à bagages l'a protégé"] },
  { id: 76, wrong: ["Les écrans pendant plus de 3h","L'air conditionné en continu","Le café à haute dose","La sédentarité complète","Le manque de sommeil chronique"] },
  { id: 77, wrong: ["Un plan pour coloniser Mars","Un protocole anti-cyberattaque","Un guide de survie nucléaire","Un manuel contre les terroristes","Un plan contre une invasion d'OVNI"] },
  { id: 78, wrong: ["Pour que ça tienne sur une étagère standard","Pour coûter moins cher à fabriquer","Parce que les premières lasers lisaient 74 min","Pour éviter les problèmes de copyright","Parce que 74 minutes est l'optimum sonore"] },
  { id: 79, wrong: ["Un adulte a 300 os, un enfant en a 100","Les os des enfants sont deux fois plus durs","Les enfants ont des os plus denses","Un enfant n'a pas de rotule","Les os des enfants ne peuvent pas se casser"] , correct: "Les enfants ont plus d'os que les adultes" },
  { id: 80, wrong: ["La Grande Muraille de Chine","Le Sahara depuis l'espace","La forêt amazonienne de nuit","Les lumières des villes la nuit","Les routes d'Europe depuis l'espace"] },
  { id: 81, wrong: ["Ils mangent tous ensemble en silence","Ils s'inclinent 30 fois par jour","Ils portent tous le même uniforme","Ils chantent l'hymne chaque matin","Ils méditent 1h avant les cours"] },
  { id: 82, wrong: ["Grotte naturelle dans une montagne","Corde utilisée par les marins","Capsule temporelle enterrée","Nœud décoratif dans les tapisseries","Petit sac de charme porté sur soi"] },
  { id: 83, wrong: ["Discours court et efficace","Jeu de mots involontaire","Traduction littérale absurde","Anecdote hors de propos","Explication inutilement longue"] },
  { id: 84, wrong: ["Elle avait un réseau d'écoute illégal","Elle avait espionné des ambassades","Elle avait volé des documents secrets","Elle avait infiltré une école","Elle avait planté un micro dans un bus"] },
  { id: 85, wrong: ["Il dormait les yeux grand ouverts","Il avait besoin de 20h de sommeil","Il rêvait toujours debout","Il s'endormait en marchant","Il avait deux cycles de sommeil par nuit"] },
  { id: 86, wrong: ["Elles ont 10 bras au lieu de 5","Elles peuvent nager à reculons","Elles changent de sexe chaque saison","Elles peuvent se détacher une branche","Elles voient uniquement les couleurs chaudes"] },
  { id: 87, wrong: ["Elles livrent des repas aux personnes âgées","Elles font des vaccinations à domicile","Elles distribuent des médicaments gratuitement","Elles proposent du yoga en ambulance","Elles ont des médecins robots embarqués"] },
  { id: 88, wrong: ["Il permet aux plantes de repousser plus vite","Il transforme le sol en compost naturel","Il filtre l'eau de pluie sous terre","Il stocke le carbone dans les racines","Il crée de l'oxygène pour les insectes"] },
  { id: 89, wrong: ["Un court-circuit dans le four","Une fuite de gaz non détectée","Un bouquet de fleurs qui a pris feu","Un cercueil trop humide","Un câble électrique surchauffé"] },
  { id: 90, wrong: ["Avoir le même prénom que toi","Être né le même mois","Avoir les mêmes empreintes digitales","Partager le même groupe sanguin","Avoir les mêmes lignes de la main"] },
  { id: 91, wrong: ["Une prise de judo interdite","Un coup de pied volant en karaté","Une figure de lutte bretonne","Une technique de boxe thai","Une clé d'épaule en jiu-jitsu"] },
  { id: 92, wrong: ["Il a mangé 200 kg de piment","Il a avalé 100 m de corde","Il a ingéré 50 kg de terre","Il a bu 300 litres d'eau","Il a mangé 80 kilos de glace"] },
  { id: 93, wrong: ["Il sculpte avec des dents humaines","Il sculpte dans des os de baleine","Il modèle avec des fientes d'oiseaux","Il grave sur des pierres précieuses","Il façonne avec des plumes d'autruche"] },
  { id: 94, wrong: ["Il change de sexe chaque saison","Il peut voler sur de courtes distances","Il se camoufle en caillou","Il marche sur l'eau sans couler","Il peut respirer par la peau"] },
  { id: 95, wrong: ["Ils sont trop petits","Ils contiennent trop de sel","Ils changent de couleur à la cuisson","Ils sentent trop fort","Ils ne peuvent pas être vendus entiers"] },
  { id: 96, wrong: ["Dans une boîte de céréales géante","Dans un congélateur industriel","Sur un float de parade","Dans son propre musée","Dans une boîte de chocolats"] },
  { id: 97, wrong: ["De la résine de bouleau","De l'extrait d'orchidée sauvage","De la sève de vanillier artificielle","Du jus de noix de coco fermenté","De la poudre de racine de yam"] },
  { id: 98, wrong: ["Il a acheté sa propre voiture","Il a signé un contrat de foot","Il a marqué un but sur un corner","Il a gagné une course de pigeons","Il a remporté un championnat de surf"] },
  { id: 99, wrong: ["Pour remplacer les câbles réseau","Pour indiquer la force du signal","Pour montrer la marque de l'appareil","Pour attirer de nouveaux clients","Pour différencier les réseaux"] },
  { id: 100, wrong: ["Elle traverse 5 pays différents","Elle est entièrement souterraine","Elle est la plus large du monde","Elle a été construite en un an","Elle est fermée la nuit"] },
  { id: 101, wrong: ["La peur des rues à sens unique","La peur de croiser des voitures","La peur de traverser en voiture","La peur des zebras piétons","La peur des grandes routes"] },
  { id: 102, wrong: ["Un gratte-ciel tournant sur lui-même","Un immeuble flottant en mer","Une ville entière sur un glacier","Une tour creuse remplie d'eau","Un pont habité de 100 km"] },
  { id: 103, wrong: ["Une vieille chaussure dépareillée","Un ticket de métro usagé","Une serviette en papier griffonnée","Une boîte d'allumettes vide","Une enveloppe déchirée"] },
  { id: 104, wrong: ["Elle peut changer de sexe","Elle peut se régénérer entièrement","Elle peut voler sur de courtes distances","Elle peut se camoufler en rocher","Elle peut survivre sans eau 1 an"] },
  { id: 105, wrong: ["Un téléphone portable","Une chaussure entière","Un sachet de billes","Une bouteille de plastique","Un stylo bille"] },
  { id: 106, wrong: ["Au sommet de l'Himalaya","Dans la forêt amazonienne","En Antarctique sous la glace","Au cœur du Sahara","Dans les alpes suisses"] },
  { id: 107, wrong: ["Il a peint depuis le sommet d'un mât","Il a flotté sur un radeau pendant 3 jours","Il a contemplé un naufrage depuis le rivage","Il a été frappé par la foudre en peignant","Il a peint depuis un sous-marin"] },
  { id: 108, wrong: ["Musée des instruments de torture","Musée du poil humain","Musée des rêves et cauchemars","Musée de la flatulence","Musée des pieds"] },
  { id: 109, wrong: ["Il change de coquille chaque semaine","Il produit un venin mortel","Il est capable de voler sur 10 mètres","Il peut vivre 10 ans sans manger","Il produit deux types de bave différents"] },
  { id: 110, wrong: ["Le record de penaltys ratés","Le record de matchs joués en carrière","Le plus de buts contre son camp","Le plus jeune buteur en finale","Le plus vieux buteur en carrière"] },
  { id: 111, wrong: ["Il avait oublié ses chaussures","Son cheval l'avait désarçonné","Il avait triché pendant la course","Il était monté sur le mauvais cheval","Il était arrivé 10 fois dernier avant"] },
  { id: 112, wrong: ["La peur des belles-filles","La peur des beaux-parents","La peur du mariage","La peur de sa propre mère","La peur des oncles"] },
  { id: 113, wrong: ["Elle peut être blanche et jaune","Elle peut peser 150 kg","Elle peut servir de casque","Elle peut être triangulaire","Elle contient une substance toxique"] },
  { id: 114, wrong: ["Il a dormi 30 jours dans un musée","Il a fait un tatouage devant le public","Il a passé 3 mois sous l'eau","Il a mangé toutes ses œuvres d'art","Il a peint en lévitant sur scène"] },
  { id: 115, wrong: ["Elle n'a pas de maire","Elle est entièrement sous l'eau","Elle est construite sur un arbre","Elle flotte sur un lac","Elle est interdite aux touristes"] },
  { id: 116, wrong: ["La peur des mains gauches","La peur des couleurs chaudes","La peur du côté droit de son corps","La peur des objets qui tournent","La peur de tourner à droite"] },
  { id: 117, wrong: ["Kim Jong-un","Mouammar Kadhafi","Adolf Hitler","Pol Pot","Idi Amin Dada"] },
  { id: 118, wrong: ["Il perd ses poils","Il arrête de courir","Il mange ses petits","Il chante en dormant","Il devient agressif envers ses alliés"] },
  { id: 119, wrong: ["Un congé pour rupture amoureuse","Un congé pour la fête d'Halloween","Un congé pour allergie saisonnière","Un congé pour anniversaire de son animal","Un congé pour mauvais résultats sportifs"] },
  { id: 120, wrong: ["Au fond des océans sur le plancher marin","Dans les météorites tombées sur Terre","Dans le noyau de la Terre en fusion","Dans les cristaux de quartz des montagnes","Dans les plantes à croissance rapide"] },
  { id: 121, wrong: ["Des billets de train","Des affiches électorales","Des symboles religieux","Des épingles à linge","Des timbres-poste"] },
  { id: 122, wrong: ["À cause des trous noirs voisins","À cause des marées lunaires","À cause des éruptions solaires","À cause des tremblements de terre","À cause des variations de pression"] },
  { id: 123, wrong: ["Vache !","Merde !","Arkansas !","Zut alors !","Sacré bleu !"] },
  { id: 124, wrong: ["Un cocktail avec un crocodile séché","Un verre avec un scorpion vivant","Une boisson avec un insecte géant","Un shot avec un ver de tequila entier","Un mojito avec une araignée"] },
  { id: 125, wrong: ["Elle flotte sur l'eau","Elle roule à l'énergie solaire","Elle est en or massif","Elle est blindée comme un char","Elle roule à l'hydrogène pur"] },
  { id: 126, wrong: ["Elle a grandi à une vitesse record","Elle est née avec deux cœurs","Elle a eu la mémoire parfaite dès la naissance","Elle a survécu à une allergie mortelle","Elle a refusé de vieillir pendant 5 ans"] },
  { id: 127, wrong: ["Sa voiture de sport","Sa montre en or","Son appartement à Las Vegas","Sa carte bancaire","Son chien de compagnie"] },
  { id: 128, wrong: ["Une ceinture oubliée dans le cockpit","Un oiseau aspiré dans le moteur","Un dé à jouer dans le tableau de bord","Une fumée de cigarette dans les instruments","Une fissure dans le hublot"] },
  { id: 129, wrong: ["Crier sans raison apparente","Rire de façon incontrôlable","Bégayer sous l'effet du stress","Éternuer plusieurs fois d'affilée","Soupirer de soulagement"] },
  { id: 130, wrong: ["Pour voir un défilé de cirque","Pour fuir une explosion de gaz","Pour assister à un match de boxe","Pour attraper un criminel fugitif","Pour voir une éclipse de soleil"] },
  { id: 131, wrong: ["Pour retrouver un tableau volé","Pour découvrir une épave de navire","Pour identifier une espèce inconnue","Pour retrouver un objet de l'espace","Pour filmer un phénomène météo rare"] },
  { id: 132, wrong: ["Des grenouilles volantes","Des serpents de mer","Des méduses transparentes","Des crabes géants","Des étoiles de mer"] },
  { id: 133, wrong: ["Interdit de les mettre dans un hôtel","Interdit de les photographier en ville","Interdit de les conduire en voiture","Interdit de les nourrir dans la rue","Interdit de les garder seuls chez soi"] },
  { id: 134, wrong: ["Il fait des pompes pour impressionner","Il construit un nid très élaboré","Il offre de la nourriture à la femelle","Il change de couleur pour séduire","Il imite le chant d'un autre animal"] },
  { id: 135, wrong: ["Elle a brûlé dans un incendie mystérieux","Elle a été fondée puis abandonnée","Elle a été décimée par une épidémie","Elle a été détruite par un cyclone","Elle a été envahie et pillée"] },
  { id: 136, wrong: ["Cuisine créative sans recette fixe","Danse traditionnelle de Bretagne","Tissu coloré fait main","Instrument de musique à vent","Animal hybride imaginaire"] },
  { id: 137, wrong: ["Comme armes de guerre catapultées","Comme espions dressés à l'écoute","Comme filets pour attraper des insectes","Comme réveils pour les soldats","Comme capteurs météo vivants"] },
  { id: 138, wrong: ["Écouter de la musique au volant","Griller un feu rouge la nuit","Doubler sur l'autoroute","Rouler sans ceinture en ville","Stationner sur le trottoir"] },
  { id: 139, wrong: ["Copier une œuvre sans le savoir","Apprendre par cœur sans comprendre","Répéter des erreurs du passé","Se souvenir d'un rêve trop vivace","Trouver une solution logique"] },
  { id: 140, wrong: ["L'œuvre a été volée par un visiteur","L'œuvre a été couverte de peinture","Un gardien a marché dessus","L'œuvre a été brûlée par accident","L'artiste l'a réclamée en urgence"] },
  { id: 141, wrong: ["Elles avaient caché les trésors du château","Elles avaient construit un tunnel secret","Elles avaient négocié une rançon","Elles avaient mis le feu aux douves","Elles avaient habillé les soldats en femmes"] },
  { id: 142, wrong: ["Il a entendu une voix inconnue","Il a reçu un appel de son double","Il a entendu un message de l'au-delà","Il a reçu un appel de lui-même","Il a entendu une conversation de la NSA"] },
  { id: 143, wrong: ["Il se mit à chanter parfaitement","Il se souvint de tout son passé","Il pouvait lire les pensées","Il parla toutes les langues","Il vit l'avenir en rêve"] },
  { id: 144, wrong: ["Ils ont tous survécu à un accident d'avion","Ils sont tous nés le même jour","Ils ont tous le même groupe sanguin","Ils ont tous 6 doigts à chaque main","Ils n'ont jamais été malades"] },
  { id: 145, wrong: ["Un incendie dans la salle d'opération","Un tremblement de terre local","Une panne de courant générale","Une fuite de gaz dans les couloirs","Un patient en crise dans le couloir"] },
  { id: 146, wrong: ["Lever un sourcil seul","Bouger ses oreilles","Toucher son nez avec sa langue","Rouler la langue en tube","Croiser les yeux volontairement"] },
  { id: 147, wrong: ["Elle change de peau en hiver","Elle nage à reculons sous la glace","Elle hiberne 9 mois par an","Elle mange sa propre peau pour se nourrir","Elle peut respirer sous la neige"] },
  { id: 148, wrong: ["Il est tatoué à 100%","Il a les ongles les plus longs","Il a la plus grande bouche","Il a les plus grandes mains","Il est le plus lourd du monde"] },
  { id: 149, wrong: ["Marmonner sans raison","Courir très vite en zigzag","Sauter à plusieurs reprises","Taper des pieds en rythme","Renifler fort sous l'effort"] },
  { id: 150, wrong: ["Elle la protège des prédateurs","Elle lui sert à nager plus vite","Elle lui permet de se camoufler","Elle lui sert à communiquer","Elle stocke de la nourriture"] },
  { id: 151, wrong: ["Le 6e continent découvert en 1900","Un fond marin inexploré","Une chaîne de montagnes sous-marine","Une forêt tropicale submergée","Un glacier de 2 millions de km2"] },
  { id: 152, wrong: ["Qui parle sans s'arrêter","Qui déteste les couleurs vives","Qui mange en faisant du bruit","Qui refuse de dormir","Qui critique tout le monde"] },
  { id: 153, wrong: ["Elle n'a pas de pont pour y accéder","Elle change de pays chaque année","Elle est interdite aux femmes","Elle est sous une bulle de verre","Elle n'a pas de nom officiel"] },
  { id: 154, wrong: ["Il ne pleut que la nuit","Il neige en été","Il n'y a aucun vent","Il y fait plus froid qu'en Antarctique","La terre y est entièrement rouge"] },
  { id: 155, wrong: ["Obsession de tout organiser","Tendance à parler sans réfléchir","Habitude de tout répéter deux fois","Peur des nouveaux environnements","Envie de tout contrôler"] },
  { id: 156, wrong: ["Il a soudoyé le juge","Il a fait pleurer le jury","Il a caché des preuves","Il a fait fuir le témoin principal","Il a invoquer un vice de procédure"] },
  { id: 157, wrong: ["Il a survécu à deux balles dans la tête","Il a survécu à une bombe en dessous de lui","Il a survécu à 3 jours sous les décombres","Il a survécu à une noyade de 10 minutes","Il a survécu à une chute de 8 étages"] },
  { id: 158, wrong: ["Elle s'était préparée pendant 10 ans","Elle portait des chaussures de sprint","Elle avait pris un taxi une partie du trajet","Elle avait le dossard d'une autre coureuse","Elle était arrivée la veille sur le parcours"] },
  { id: 159, wrong: ["Personne ne savait nager à la cour","Le fleuve était considéré sacré","Les gardes avaient peur d'être punis","La reine voulait mourir en paix","Les serviteurs étaient tous attachés"] },
  { id: 160, wrong: ["Pour éviter de se lever pour changer de chaîne","Pour allumer la télé depuis le lit","Pour contrôler le volume sans se lever","Pour zapper depuis la salle de bain","Pour éteindre la télé sans se déranger"] },
  { id: 161, wrong: ["De calcium pur cristallisé","D'eau salée sous pression","De minéraux issus des comètes","De lumière solaire fossilisée","D'atomes d'or en suspension"] },
  { id: 162, wrong: ["Napoléon Bonaparte","Abraham Lincoln","Sherlock Holmes","Batman","Harry Potter"] },
  { id: 163, wrong: ["Ils ont mangé leurs chaussures en cuir","Ils ont mangé les racines des arbres","Ils ont bu l'eau des radiateurs","Ils ont mangé leur ceinture","Ils ont fait bouillir de l'herbe sèche"] },
  { id: 164, wrong: ["La peur de manger du beurre de cacahuète","La peur des arachides en général","La peur des beurres épais","La peur de s'étouffer en mangeant","La peur des pâtes à tartiner"] },
  { id: 165, wrong: ["Courir plus vite que les lions","Nager sous l'eau 5 minutes","Manger à l'envers","Dormir debout sur ses 4 pattes","Voir derrière elle sans tourner la tête"] },
  { id: 166, wrong: ["Il est tombé de son cheval en compétition","Il a plongé dans une piscine vide","Il a été frappé par la foudre","Il s'est noyé en traversant une rivière","Un rocher lui est tombé dessus"] },
  { id: 167, wrong: ["Un nuage de glace sur Mars","Une tempête de sable au Sahara","Un banc de nuages d'orage","Une aurore boréale en hiver","Un cyclone de catégorie 5"] },
  { id: 168, wrong: ["Titanic","Retour vers le futur","Jurassic Park","Le Roi Lion","Forrest Gump"] },
  { id: 169, wrong: ["Plongeur sous-marin","Pilote de chasse","Archéologue de terrain","Chirurgien cardiaque","Alpiniste professionnel"] },
  { id: 170, wrong: ["Il avait une peau transparente","Il n'avait pas de pigments dans la peau","Il avait des écailles au lieu d'ongles","Il avait des membranes entre les doigts","Il avait une peau qui brillait dans le noir"] },
  { id: 171, wrong: ["Le numéro 7","Le numéro 0","Le numéro 666","Le numéro 4","Le numéro 8"] },
  { id: 172, wrong: ["Il peut vivre 10 ans sans manger","Il peut changer de sexe chaque saison","Il peut respirer dans l'air et sous l'eau","Il peut se camoufler parfaitement","Il peut survivre à -200°C"] },
  { id: 173, wrong: ["Il sculpte avec des cheveux humains","Il grave sur des os d'animaux","Il peint avec de la boue volcanique","Il tisse avec des fils d'or","Il crée avec des cendres humaines"] },
  { id: 174, wrong: ["La rivière la plus courte du monde","Le soleil de minuit","Un glacier qui parle","Un lac sans fond connu","Une avalanche en plein été"] },
  { id: 175, wrong: ["Elles les voient avec leurs antennes","Elles les détectent par leur parfum","Elles les repèrent à leur couleur","Elles les entendent depuis 1 km","Elles les ressentent par vibration"] },
  { id: 176, wrong: ["Des algues vertes séchées","Un cachalot échoué","De l'huile de poisson ramenée","Des coquillages broyés","Des poissons morts dans les filets"] },
  { id: 177, wrong: ["Interdit d'utiliser son téléphone","Interdit de marcher sur la pelouse","Interdit de klaxonner la nuit","Interdit de sortir après 22h","Interdit de jouer de la musique en plein air"] },
  { id: 178, wrong: ["De tickets de cinéma","De capsules de bière","De cartes postales","De gommes à mâcher usagées","D'étiquettes de bagages"] },
  { id: 179, wrong: ["Des vers intestinaux géants","Des araignées microscopiques","Des champignons parasites","Des bactéries fluorescentes","Des algues filamenteuses"] },
  { id: 180, wrong: ["Pour s'amuser entre amis","Pour tester les moteurs de vapeur","Pour simuler les montagnes des Alpes","Pour faire voyager sans bouger","Pour transporter du charbon en ville"] },
  { id: 181, wrong: ["Il change de couleur selon l'humeur","Il gonfle quand on le mouille","Il rétrécit à la chaleur","Il change de goût au bout de 5 minutes","Il reste mâché pour toujours"] },
  { id: 182, wrong: ["L'art de lire les pensées","Le langage des signes médiéval","La prédiction par les rêves","La mémoire des traumatismes","L'étude des maladies de l'âme"] },
  { id: 183, wrong: ["Un casque de chevalier médiéval","Un vase de l'Antiquité grecque","La perruque de Marie-Antoinette","Un fragment de météorite"] },
  { id: 184, wrong: ["Elle avait prédit sa mort dans son journal","Elle a chanté en se réveillant","Elle a frappé le cercueil de l'intérieur","Elle a souri pendant la cérémonie","Elle a demandé à rentrer à la maison"] },
  { id: 185, wrong: ["Phrase sans queue ni tête","Discours ampoulé et pompeux","Texte écrit à l'envers","Longue liste de mots difficiles","Silence prolongé pendant un discours"] },
  { id: 186, wrong: ["Manger un burger","Conduire sans permis","Dormir sur la plage","Appeler un inconnu","Chanter dans la rue"] },
  { id: 187, wrong: ["Mot inventé par un enfant","Erreur de traduction célèbre","Phrase coupée au début","Exclamation populaire","Expression figée idiomatique"] },
  { id: 188, wrong: ["La peur des horloges","La peur des patrons","La peur des réunions longues","La peur des collègues bruyants","La peur des heures supplémentaires"] },
  { id: 189, wrong: ["Pour les chasser de leur territoire","Pour manger leurs parasites","Pour jouer avec eux","Pour les utiliser comme boucliers","Pour se camoufler parmi eux"] },
  { id: 190, wrong: ["Ils ont tous le même prénom","Ils ont tous la même voiture","Ils vivent tous sur le même lac","Ils sont tous jumeaux","Ils ont tous le même employeur"] },
  { id: 191, wrong: ["Un cercle de hula-hoop","Une bouteille d'un litre","Un tuyau de 30 cm","Un panier de basket","Un anneau de 50 cm"] },
  { id: 192, wrong: ["Des traces de médicaments","Des résidus de plastique","Des particules de métal","Des traces de peinture","Des restes de sol industriel"] },
  { id: 193, wrong: ["Il était devenu entièrement vert","Il avait perdu toute sa peau","Il avait les cheveux qui repoussaient blancs","Il voyait tout en rose","Il avait des dents qui brillaient"] },
  { id: 194, wrong: ["Petite erreur grammaticale répandue","Style vestimentaire baroque","Instrument à vent improvisé","Animal imaginaire des Pyrénées","Jeu de cartes régional"] },
  { id: 195, wrong: ["Ils sont comestibles en cas de survie","Ils changent de couleur à l'humidité","Ils émettent un son sous UV","Ils peuvent se déchirer sans se décoller","Ils flottent sur l'eau"] },
  { id: 196, wrong: ["Il avait deux visages distincts","Il avait des branchies dans le cou","Il n'avait pas d'oreilles","Il avait les pieds retournés","Il avait deux cœurs qui battaient"] },
  { id: 197, wrong: ["Les ongles","Les dents","Les os du crâne","Les cartilages des oreilles","Les poils"] },
  { id: 198, wrong: ["Se souvenir de ses vies passées","Guérir ses maladies par la pensée","Voyager dans le temps en dormant","Lire les pensées des autres","Percevoir les événements futurs"] },
  { id: 199, wrong: ["Cuisine moléculaire spectaculaire","Art de décorer les gâteaux","Cuisine préparée en 3D","Aliments imprimés par laser","Nourriture comestible à base de pixels"] },
  { id: 200, wrong: ["Il avait deux cerveaux fonctionnels","Il pouvait lire à l'envers","Il avait un troisième œil","Il avait une mémoire photographique","Il n'avait pas de douleur"] },
  { id: 201, wrong: ["Des vaccins contre les virus","Des pièces de moteur spatial","Des cristaux de météorite","Du carburant liquide","Des vêtements en nanofibre"] },
  { id: 202, wrong: ["Elle improvisait des opéras en entier","Elle composait de la musique en dormant","Elle jouait plusieurs instruments à la fois","Elle percevait la musique comme des couleurs","Elle battait les pianistes professionnels"] },
  { id: 203, wrong: ["\"Bonne nuit à tous les auditeurs\"","\"Nous interrompons cette émission\"","\"Ceci est un message d'urgence\"","\"Le gouvernement est tombé ce soir\"","\"Une catastrophe vient de se produire\""] },
  { id: 204, wrong: ["Il est mort en mangeant trop vite","Il est tombé de son cheval royal","Il est mort d'un fou rire en public","Il a été frappé par sa propre épée","Il a été étranglé par son écharpe"] },
  { id: 205, wrong: ["Elle court plus vite que les autres enfants","Elle a une mémoire absolument parfaite","Elle parle 10 langues depuis l'enfance","Elle ne dort que 2 heures par nuit","Elle soulève 3 fois son poids"] },
  { id: 206, wrong: ["80% portent des traces d'urine","50% ont été volés au moins une fois","75% contiennent des germes d'hôpital","60% ont des traces de larmes","95% sont faux dans le monde"] },
  { id: 207, wrong: ["Le Pacifique se rétrécit chaque année","L'Afrique se divise en deux lentement","La Méditerranée se ferme progressivement","L'Atlantique s'élargit de 5 cm par an","L'Australie dérive vers l'Asie"] },
  { id: 208, wrong: ["Les chaussures doivent être enlevées","Il est interdit de courir dans le terminal","Les adieux sont filmés obligatoirement","Les chiens sont interdits dans les halls","Les cadeaux doivent être déclarés"] },
  { id: 209, wrong: ["On leur enlevait le cœur en dernier","On leur injectait du sable chaud","On leur brûlait les extrémités","On leur brisait les os des membres","On leur retirait les dents"] },
  { id: 210, wrong: ["Il portait un deuxième squelette","Ses poumons fonctionnaient par machine","Son cerveau était partiellement artificiel","Il vivait dans une bulle stérile","Sa circulation sanguine était externe"] },
  { id: 211, wrong: ["Attacher sa ceinture de sécurité","Allumer les phares avant de démarrer","Signaler sa direction avant de partir","Vérifier le niveau d'huile","Activer le GPS avant de rouler"] },
  { id: 212, wrong: ["Il a sucé le venin lui-même","Il a appliqué de la boue sur la plaie","Il a immergé son bras dans de l'eau froide","Il a couru pour accélérer son sang","Il a fait un garrot avec sa ceinture"] },
  { id: 213, wrong: ["Ils ont créé des rats invisibles","Ils ont fabriqué des chats robots","Ils ont cloné un tigre blanc","Ils ont cultivé des plantes sans eau","Ils ont créé des poissons volants"] },
  { id: 214, wrong: ["Un buffet à volonté","Un bar à sushis dès 7h","Un massage offert pendant le repas","Une garde d'enfants pendant le dîner","Un concert live tous les soirs"] },
  { id: 215, wrong: ["La peine de mort","L'interdiction de vote","La ségrégation raciale","La polygamie forcée","L'emprisonnement sans jugement"] },
  { id: 216, wrong: ["Ses propres larmes","Du sable de plage","Des ailes d'insectes","De la cire d'abeilles","Des grains de poussière"] },
  { id: 217, wrong: ["Elle a déplacé les habitants en altitude","Elle a creusé un tunnel vers le soleil","Elle a peint le sol en blanc","Elle a planté des arbres lumineux","Elle a installé des lampes en bordure"] },
  { id: 218, wrong: ["Il avait tué un baron local","Il avait volé dans la cathédrale","Il avait prédit la mort du roi","Il avait sorcellé des paysans","Il avait violé la loi sur les moulins"] },
  { id: 219, wrong: ["Pour acheter une propriété","Pour ouvrir un temple","Pour changer de nom","Pour faire un voyage à l'étranger","Pour publier un livre sacré"] },
  { id: 220, wrong: ["La montagne était trop éclairée","Des yeux rouges apparaissaient dans la neige","La brume rendait tout violet","Les skis laissaient des traces blanches","La neige était couverte de sable doré"] },
  { id: 221, wrong: ["Il a sauté d'un avion en feu","Il a nageé dans de la lave froide","Il s'est fait frapper 200 fois","Il a traversé un champ de mines","Il a conduit une moto à travers un mur"] },
  { id: 222, wrong: ["Respirer profondément","Regarder un point fixe","Fermer les yeux et compter","Écrire une liste de tâches","Écouter une musique douce"] },
  { id: 223, wrong: ["Elle a sauté d'un avion sans parachute","Elle a traversé l'Atlantique à la nage","Elle a nagé sous un iceberg en hiver","Elle a traversé le Niagara en kayak","Elle a plongé depuis une falaise de 60m"] },
  { id: 224, wrong: ["La peur des cauchemars","La peur des mauvais présages","La peur de l'avenir","La peur des phobies des autres","La peur d'être effrayé en public"] },
  { id: 225, wrong: ["La peur de la philosophie","La peur des intellectuels","La peur des bibliothèques","La peur des livres trop denses","La peur des questions sans réponse"] },
  { id: 226, wrong: ["Elle roule grâce à l'énergie éolienne","Elle roule avec du lait de vache","Elle fonctionne au méthane animal","Elle avance avec de la levure de bière","Elle roule à l'huile de friture"] },
  { id: 227, wrong: ["Elle peut prédire les maladies","Elle parle 40 langues couramment","Elle calcule mentalement comme un ordinateur","Elle entend les conversations à 2 km","Elle reconnaît 10 000 visages différents"] },
  { id: 228, wrong: ["Une assurance contre les accidents de ski","Une assurance contre les morsures de requin","Une assurance contre les chutes d'astéroïde","Une assurance contre la possession démoniaque","Une assurance contre les cataclysmes naturels"] },
  { id: 229, wrong: ["Elle a disparu en pleine nuit","Elle a été copiée 1000 fois","Elle a été brûlée par un acheteur","Elle a été refusée par tous les musées","Elle a causé un scandale mondial"] },
  { id: 230, wrong: ["L'artiste a refusé de la vendre","Elle a été volée pendant la nuit","Elle a été détruite par un visiteur","Un galeriste l'a accrochée à l'envers","Elle a changé de valeur 100 fois en un jour"] },
  { id: 231, wrong: ["La peur des citrons","La peur du soleil","La peur des cheveux blonds","La peur de l'or","La peur des fleurs jaunes"] },
  { id: 232, wrong: ["Il a évacué le Pentagone","Il a détourné des satellites","Il a lancé une frappe militaire","Il a fermé une frontière nationale","Il a arrêté un réseau terroriste"] },
  { id: 233, wrong: ["Il a mangé un kilo de neige","Il a dormi debout 3 jours","Il a chanté 50 chansons d'affilée","Il a fait 500 selfies en 1 minute","Il a porté un chapeau pendant 10 ans"] },
  { id: 234, wrong: ["Une patate douce","Un concombre","Une pierre volcanique","Un champignon","Une carotte fraîche"] },
  { id: 235, wrong: ["Il produit de l'insuline tout seul","Il filtre le sang en continu","Il stocke toute l'eau du corps","Il commande tous les mouvements","Il régule la température du corps"] },
  { id: 236, wrong: ["La peur des fauteuils hauts","La peur des surfaces molles","La peur de s'endormir assis","La peur des escaliers","La peur des transports assis"] },
  { id: 237, wrong: ["Elle peut survivre à -200°C","Elle peut vivre sans eau 100 ans","Elle peut se cloner par simple contact","Elle peut respirer à la fois air et eau","Elle peut résister à un acide fort"] },
  { id: 238, wrong: ["Il s'est fait propulser par une explosion","Il a sauté depuis un avion supersonic","Il a été éjecté d'une voiture à 200 km/h","Il a été frappé par une vague géante","Il a été lancé par un tremplin géant"] },
  { id: 239, wrong: ["Il était trop sombre à reproduire","Il a été interdit par les artistes peintres","Il n'a pas de longueur d'onde précise","Il a été inventé après les autres couleurs","Il ne peut pas être vu en lumière vive"] },
  { id: 240, wrong: ["On a oublié le sucre dans la pâte","Une recette a été écrite à l'envers","Un chef a renversé de la vanille","La farine a été brûlée par erreur","Un four a mal réglé la température"] },
  { id: 241, wrong: ["Les bébés marchent dès 3 mois","Les enfants choisissent leur prénom","L'école commence à 3 ans","On fête les anniversaires en avance","On ne célèbre pas les anniversaires"] },
  { id: 242, wrong: ["Une panne nationale d'électricité","Une erreur de logiciel de vote","Un séisme pendant le dépouillement","Un virus informatique dans les urnes","Une fraude massive aux bulletins"] },
  { id: 243, wrong: ["Ils portent le même vêtement depuis 20 ans","Ils ont la même empreinte digitale","Ils lisent le même livre depuis 20 ans","Ils prennent les mêmes repas depuis 20 ans","Ils n'ont pas de miroir chez eux"] },
  { id: 244, wrong: ["Elle a accouché sous anesthésie générale","Elle a eu des sextuplés","Elle est morte pendant l'accouchement","Elle a été la plus vieille mère du monde","Elle a accouché de deux bébés en 2 jours"] },
  { id: 245, wrong: ["Dans une ferme isolée en Islande","Au fond d'une mine en Sibérie","Dans un bunker au Groenland","Dans un phare automatisé","Dans un observatoire polaire"] },
  { id: 246, wrong: ["La vie est apparue avant les étoiles","La Terre est la seule planète vivante","L'univers est trop vieux pour la vie","La vie vient exclusivement des océans","Dieu a créé les organismes vivants"] },
  { id: 247, wrong: ["Elle pèse 50 tonnes","Elle parle quand on l'approche","Elle change de couleur selon la lumière","Elle est composée de 1000 matériaux","Elle se déplace lentement"] },
  { id: 248, wrong: ["De calendriers de banques","De cure-dents usagés","De billets de trains périmés","De sachets de sucre vides","De cartes de visite froissées"] },
  { id: 249, wrong: ["À détruire les insectes ennemis","À produire du venin concentré","À détecter les odeurs à distance","À aspirer l'eau dans les mares","À émettre des sons ultrasoniques"] },
  { id: 250, wrong: ["Par accident en testant un congélateur","En voulant faire du pain glacé","En cherchant à congeler de la crème","En laissant un verre à l'air froid","En oubliant une soupe au balcon"] },
  { id: 251, wrong: ["Écriture codée utilisée par les espions","Technique de calligraphie indienne","Style de dessin en spirale","Langue parlée par une seule tribu","Système de chiffrement informatique"] },
  { id: 252, wrong: ["Un château hanté en Écosse","Une plage introuvable sur les cartes","Un village fantôme dans les highlands","Le lac Ness et son monstre","Un festival de cornemuse annuel"] },
  { id: 253, wrong: ["Peur du numéro 13","Peur du numéro 0","Peur des chiffres en général","Peur du numéro 13 le vendredi","Peur des suites mathématiques"] },
  { id: 254, wrong: ["Des habitants avaient envahi le tracé","Des maisons bloquaient le passage","Le coût était trop élevé","Un vestige romain avait été découvert","Un lac souterrain était sur le trajet"] },
  { id: 255, wrong: ["Il a dormi sans rêver pendant 11 jours","Il a parlé pendant 11 jours sans pause","Il a couru pendant 11 jours d'affilée","Il a chanté pendant 11 jours","Il n'a pas bougé pendant 11 jours"] },
  { id: 256, wrong: ["Il est le plus poilu du monde","Il a les ongles les plus longs","Il est le plus grand au monde","Il pèse le moins au monde","Il est le plus petit du monde"] },
  { id: 257, wrong: ["Qui brille dans l'obscurité totale","Qui change de texture selon la chaleur","Qui est doux comme de la soie","Qui est parfaitement transparent","Qui a un goût sucré naturel"] },
  { id: 258, wrong: ["Il a éternué sans arrêt","Il a pleuré pendant 68 ans","Il a dormi en position assise","Il a ri involontairement pendant des années","Il a été paralysé des bras"] },
  { id: 259, wrong: ["Il a nagé en tenant une corde","Il a traversé à bord d'un jet-ski","Il a flottté sur un radeau de fortune","Il a traversé en planche de surf","Il a nagé sous l'eau sur 30 km"] },
  { id: 260, wrong: ["Pour aller déjeuner en dehors","Pour récupérer leurs enfants à l'école","Pour se rendre à un rendez-vous médical","Pour éviter les transports bondés","Pour prendre du repos après un examen"] },
  { id: 261, wrong: ["Elle a vendu ses ongles aux enchères","Elle a offert ses ongles à un musée","Elle les a encadrés comme des œuvres d'art","Elle les a données à la science","Elle les a transformées en bijoux"] },
  { id: 262, wrong: ["Entendre les sons comme des formes","Ressentir la douleur comme une couleur","Compter les objets en musique","Confondre des chiffres et des lettres","Voir des nombres en couleur"] },
  { id: 263, wrong: ["La peur du rasage","La peur des hommes âgés","La peur des poils longs","La peur des visages couverts"] },
  { id: 264, wrong: ["Israël avait vendu des armes à l'Égypte","Israël avait espionné des généraux","Israël avait capturé un pêcheur égyptien","Israël n'avait pas payé une dette","Israël avait construit un mur frontalier"] },
  { id: 265, wrong: ["Un spectacle de magie impressionnant","Une attaque aérienne à proximité","Un cambriolage en plein casino","Un tremblement de terre sous la salle","Un blackout total pendant 3 heures"] },
  { id: 266, wrong: ["On mange assis dans une piscine","On cuisine soi-même à table","On mange dans l'obscurité totale","On dîne en suspendus dans les airs","On mange dans un cercueil ouvert"] },
  { id: 267, wrong: ["La peur des démons","La peur des cicatrices","La peur d'être incompris","La peur du regard des autres","La peur de l'inconnu"] },
  { id: 268, wrong: ["Il s'était enfui dans la forêt","Il avait perdu la mémoire totalement","Il avait dormi sans s'arrêter","Il était paralysé des deux jambes","Il avait perdu l'usage de la parole"] },
  { id: 269, wrong: ["La peur du chiffre 3","La peur des nombres impairs","La peur du chiffre 7","La peur de compter à voix haute","La peur des calendriers"] },
  { id: 270, wrong: ["Il avait insulté la famille royale","Il avait chanté trop fort","Il n'avait pas de visa valide","Il avait refusé de payer un droit d'entrée","Il avait photographié des gardes"] },
  { id: 271, wrong: ["Il a explosé en dégustant son whisky","Il a été empoisonné par ses tonneaux","Il a été renversé par un cheval ivre","Il s'est noyé dans une cuve de distillation","Il est mort d'une intoxication alcoolique"] },
  { id: 272, wrong: ["Interdit de fuir vers un autre pays","Interdit de changer de nom en fuite","Interdit de se faire aider par des amis","Interdit de contacter un avocat","Interdit de fuir par voie maritime"] },
  { id: 273, wrong: ["On brûlait des herbes odorantes","On se baignait dans du vinaigre","On mangeait de l'ail à chaque repas","On portait des amulettes spéciales","On priait 10 fois par jour"] },
  { id: 274, wrong: ["Des cacahuètes non déclarées","Un saucisson artisanal","Du fromage fait maison","Des graines de tournesol","Une bouteille d'eau non étiquetée"] },
  { id: 275, wrong: ["Une cacahuète","Un chat orange","Un raton laveur","Une souris jaune","Un lapin électrique"] },
  { id: 276, wrong: ["La peur des prêtres","La peur des icônes religieuses","La peur des confessions","La peur des bénédictions","La peur du Vatican"] },
  { id: 277, wrong: ["La peur des bouteilles de parfum","La peur de la transpiration","La peur des vestiaires","La peur des déodorants","La peur de sentir bon"] },
  { id: 278, wrong: ["Des beignets de cactus","Des tartes aux insectes","Des glaces à la moutarde","Des brochettes de ver de terre","Des bonbons au piment brûlant"] },
  { id: 279, wrong: ["Le jour le plus froid de l'année","Le jour de la grande purge des frigos","Le jour du plus grand match de NFL","Le jour où tous les Américains déménagent","Le jour de la plus longue file à Walmart"] },
  { id: 280, wrong: ["Pour colorer les plats","Pour parfumer les préparations","Pour faire mousser les sauces","Pour décorer les assiettes","Pour attendrir la viande"] },
  { id: 281, wrong: ["Le miel","La fraise des bois","Le sel de mer","Le jus de citron","L'ail séché"] },
  { id: 282, wrong: ["On perd du poids en dormant","Le cerveau grossit le soir","Les ongles poussent deux fois plus vite","Le sang devient plus rouge la nuit","La température du corps monte de 2°C"] },
  { id: 283, wrong: ["Chercher des poux dans les cheveux","Tricoter très rapidement sans s'arrêter","Parler fort en marchant","Nager comme une grenouille","Siffler en expirant par le nez"] },
  { id: 284, wrong: ["Des mers d'eau liquide","Des forêts de cristaux de glace","Des déserts de sable noir","Des lacs de méthane","Des montagnes de soufre"] },
  { id: 285, wrong: ["Rivière souterraine de l'Amazonie","Grande salle de bal du XVIIe siècle","Monnaie médiévale de cuivre","Instrument à cordes artisanal","Peuple nomade du Maghreb"] },
  { id: 286, wrong: ["Elle appartient à deux pays différents","Elle est la plus grande île d'Asie","Elle n'a pas de côte maritime","Elle est entièrement artificielle","Elle est couverte à 90% de forêt vierge"] },
  { id: 287, wrong: ["Elle peut retourner sa carapace","Elle respire par les branchies et les poumons","Elle peut nager en marche arrière","Elle dort les yeux ouverts","Elle peut se mettre en boule"] },
  { id: 288, wrong: ["Un verre qui change de couleur","Un verre qui joue de la musique","Un verre qui filtre l'alcool","Un verre qui indique l'heure","Un verre qui se remplit seul"] },
  { id: 289, wrong: ["La peur des oiseaux chanteurs","La peur des concerts de musique","La peur des instruments à cordes","La peur des sifflets","La peur des orchestres"] },
  { id: 290, wrong: ["L'espace entre la Lune et la Terre","Le fond de l'océan Pacifique","La calotte polaire de l'Arctique","Le désert du Sahara central"] },
  { id: 291, wrong: ["Sa veste en cuir épais a résisté","Elle portait un gilet pare-balles","Un livre dans sa poche a dévié la balle","Son téléphone a absorbé l'impact","Un bracelet en métal a redirigé la balle"] },
  { id: 292, wrong: ["Inventer des explications improbables","Parler en regardant le sol","Répéter les mots des autres","Critiquer sans proposer de solution","Faire semblant de comprendre"] },
  { id: 293, wrong: ["Il avait un deuxième visage dans la nuque","Il n'avait pas d'yeux","Il pouvait retourner ses bras","Il avait six doigts de chaque côté","Il marchait sur les mains naturellement"] },
  { id: 294, wrong: ["Il avait été blessé par un policier","Il avait été victime d'une fraude","Il avait perdu ses économies en prison","Il avait souffert de mauvais traitements","Il avait été condamné pour un crime mineur"] },
  { id: 295, wrong: ["Plante grimpante à fleurs rouges","Sauce pimentée d'Amérique du Sud","Minéral brillant des volcans","Tissu rugueux utilisé en poterie","Technique de pêche à la main"] },
  { id: 296, wrong: ["Elle attire plus de 10 millions de pigeons","Elle génère plus d'éclairs que la normale","Elle reçoit plus de photos qu'Instagram","Elle vibre légèrement à cause du vent","Elle diffuse de la musique par ses structures"] },
  { id: 297, wrong: ["Il a avalé un poison accidentellement","Il s'est étouffé avec une arête de poisson","Il a été frappé par la foudre","Il a coulé dans une rivière gelée","Il a bu de l'eau en dormant"] },
  { id: 298, wrong: ["Il ne dormait que 5 minutes par nuit","Il ne respirait que par la bouche","Il courrait 50 km chaque matin","Il méditait sous l'eau 2 heures par jour","Il ne parlait qu'à ses élèves"] },
  { id: 299, wrong: ["Ils changent de couleur en rythme","Ils produisent des ultrasons musicaux","Ils laissent des traces parfumées","Ils dansent pour se reconnaître","Ils gonflent leur gorge pour crier"] },
  { id: 300, wrong: ["Dormir sans bouger du tout","Parler dans son sommeil","Ronfler très fort","Se gratter la nuit","Avoir des apnées fréquentes"] },
  { id: 301, wrong: ["Long texte indéchiffrable","Déclaration solennelle officielle","Trait d'humour subtil","Erreur de français répandue","Formule magique ancienne"] },
  { id: 302, wrong: ["La peur des regards dans les miroirs","La peur de se voir en photo","La peur des regards intenses","La peur de regarder en bas","La peur de regarder en haut"] },
  { id: 303, wrong: ["Qui brûle facilement","Qui se décompose vite","Qui absorbe l'eau","Qui résiste au froid","Qui attire les parasites"] },
  { id: 304, wrong: ["Les nuages","Les montagnes","Les rivières","Les glaciers","Les volcans"] },
  { id: 305, wrong: ["La peur des bruits de ventre","La peur de se lâcher en public","La peur des odeurs","La peur des toilettes publiques","La peur d'avoir besoin d'aller aux WC"] },
  { id: 306, wrong: ["Une épée en bronze","Un vase celtique","Un fragment de rune gravée","Un jouet en argile","Un crâne humain peint"] },
  { id: 307, wrong: ["La peur des fantômes","La peur des sorcières","La peur du diable","La peur des zombies","La peur du Père Fouettard"] },
  { id: 308, wrong: ["Il y a plus de brebis que de vaches","Il y a plus de méduses que de poissons","Il y a plus de crocodiles que d'humains","Il y a plus de serpents que d'habitants","Il y a plus de chauves-souris que de moutons"] },
  { id: 309, wrong: ["On peut se marier à 14 ans","On peut se marier sans cérémonie","On peut se marier sous l'eau","On peut se marier en prison","On peut se marier en avion"] },
  { id: 311, wrong: ["Un seul arbre en pot","Un seul couteau de cuisine","Un seul chien de compagnie","Un seul aquarium chez soi","Un seul vélo par adulte"] },
  { id: 312, wrong: ["La multiplication","La division","La racine carrée","Les fractions","La géométrie"] },
  { id: 313, wrong: ["Un os coincé dans la gorge","Un insecte dans le sinus","Un fragment de verre dans les poumons","Un calcaire dans les bronches","Un grain de sable dans la plèvre"] },
  { id: 314, wrong: ["Damn it !","I love you !","Holy cow !","Oh my god !","Son of a gun !"] },
  { id: 316, wrong: ["Il avait des champignons dans le nez","Il avait une balle coincée","Il avait de la colle dans les poumons","Il avait une écharpe dans les bronches","Il avait de la mousse dans les sinus"] },
  { id: 317, wrong: ["Mort en tombant d'un arbre","Mort par un excès de sommeil","Mort en pleine baignade","Mort en courant un marathon","Mort en pleine nuit sans raison"] },
  { id: 318, wrong: ["Il peut parler aux autres rennes","Il vole plus vite que les autres","Il connaît toutes les maisons du monde","Il ne se fatigue jamais","Il peut voir dans le noir total"] },
  { id: 319, wrong: ["Elle a vécu 100 ans en parfaite santé","Elle a eu des triplés à 80 ans","Elle s'est réveillée d'un coma de 50 ans","Elle a été ressuscitée par choc électrique","Elle a survécu à deux noyades"] },
  { id: 320, wrong: ["Il a nagé 500 m à l'âge de 4 ans","Il a marché 10 km seul","Il a mémorisé 1000 mots en un jour","Il a résolu un Rubik's Cube","Il a sauté à la corde 500 fois"] },
  { id: 321, wrong: ["La Banque de France","L'Opéra de Paris","La Cave du Louvre","Les Cristalleries de Saint-Louis","Les Hospices de Beaune"] },
  { id: 322, wrong: ["Il a couru pieds nus sur de la glace","Il a terminé sans jamais s'arrêter","Il a battu le record du monde à 90 ans","Il a couru en portant son dossard à l'envers","Il a terminé en chantant"] },
  { id: 323, wrong: ["Il pond sans jamais s'accoupler","Il peut nager à reculons","Il peut changer de couleur du plumage","Il peut voler à 200 km/h","Il chante de nuit comme un rossignol"] },
  { id: 324, wrong: ["Il a été mordu par le même serpent","Il a survécu à 7 naufrages","Il a gagné à la loterie 7 fois","Il a survécu à 7 accidents de voiture","Il a été opéré 7 fois du même organe"] },
  { id: 325, wrong: ["Vol de nid dans les arbres","Vol de pollen entre fleurs","Vol de proies entre prédateurs","Vol de nourriture entre singes","Vol de territoire entre fourmis"] },
  { id: 326, wrong: ["Un phare côtier actif depuis 200 ans","Une bougie qui brûle sans s'éteindre","Une batterie fonctionnant depuis 150 ans","Un moulin à vent du Moyen Âge","Un four alimenté au bois sans interruption"] },
  { id: 327, wrong: ["Pour coller des notes dans les bureaux","Pour marquer les pages d'un livre","Pour noter les courses au supermarché","Pour fixer des photos sur un frigo","Pour décorer les cahiers d'écoliers"] },
  { id: 328, wrong: ["Pablo Picasso","Joan Miró","Andy Warhol","René Magritte","Marc Chagall"] },
  { id: 329, wrong: ["Elle est construite sur l'eau","Elle est dirigée par des prisonniers","Elle est entourée de mines terrestres","Elle est creusée dans une falaise","Elle est invisible depuis la route"] },
  { id: 330, wrong: ["Ils imitent la voix humaine parfaitement","Ils retournent des cadeaux à leurs ennemis","Ils jouent des tours aux passants","Ils se suicident collectivement","Ils plient des brindilles en formes géométriques"] },
  { id: 331, wrong: ["Les chaussures à talons","Les casquettes de baseball","Les stylos bille","Les bonbons en sachet","Les parapluies colorés"] },
  { id: 332, wrong: ["Pour éviter que les animaux ne les déterrent","Pour économiser le bois de cercueil","Pour marquer leur territoire familial","Pour indiquer le rang social du défunt","Pour faire tenir les fleurs dessus"] },
  { id: 333, wrong: ["Elle a payé une taxe spéciale","Elle a bricolé les cahiers des élèves","Elle a embauché des acteurs","Elle a construit une classe fictive","Elle a déplacé l'école dans un autre bâtiment"] },
  { id: 334, wrong: ["Il avait des cornes qui poussaient","Il avait la peau qui brillait la nuit","Il avait des dents qui ne tombaient jamais","Il avait des oreilles comme un animal","Il avait le corps recouvert de plumes"] },
  { id: 335, wrong: ["Quand il voit un prédateur","Quand il cherche sa nourriture","Quand il protège ses petits","Quand il marque son territoire","Quand il rencontre un rival"] },
  { id: 336, wrong: ["L'obligation de voter","L'obligation de porter un chapeau","L'obligation de saluer ses voisins","L'obligation de s'excuser après un bruit","L'obligation de cirer ses chaussures"] },
  { id: 337, wrong: ["Il a survécu à un séisme de magnitude 9","Il a survécu à 3 tsunamis consécutifs","Il a survécu à un tir de missile","Il a survécu à une éruption volcanique","Il a survécu à un effondrement de mine"] },
  { id: 338, wrong: ["Style d'écriture médiéval décoratif","Type de dentelle aux fuseaux","Coupe de viande en boucherie","Mélodie répétée en boucle","Ancienne mesure de longueur"] },
  { id: 339, wrong: ["La peur des masques de carnaval","La peur du maquillage excessif","La peur des acteurs de théâtre","La peur des déguisements","La peur des personnages de cirque"] },
  { id: 340, wrong: ["Sa lune est faite de glace pure","Son noyau est entièrement liquide","Ses aurores sont permanentes","Sa surface est entièrement couverte d'eau","Ses anneaux sont solides comme du béton"] },
  { id: 341, wrong: ["Il a jeûné pendant 50 ans","Il a récité des prières 10 000 fois","Il a marché pieds nus sur des braises","Il a médité au fond d'une rivière froide","Il a porté des chaînes pendant 30 ans"] },
  { id: 342, wrong: ["Interdit de le faire courir en ville","Interdit de lui faire traverser la rue","Interdit de l'amener dans un avion","Interdit de lui faire porter un harnais","Interdit de l'approcher à moins de 10m"] },
  { id: 343, wrong: ["Il a appris 200 langues","Il a lu 10 000 livres en un an","Il a mémorisé tous les codes postaux","Il a retenu les paroles de 5000 chansons","Il a mémorisé chaque visage vu en 30 ans"] },
  { id: 344, wrong: ["Les femelles pondent sans se reproduire","Ils changent de sexe selon la saison","Ils peuvent vivre 50 ans sans manger","Ils flottent sans nager","Ils vivent collés deux à deux à vie"] },
  { id: 345, wrong: ["Ce logiciel prédit les crises d'épilepsie","Ce logiciel traduit les aboiements","Ce logiciel analyse les rêves enregistrés","Ce logiciel contrôle l'humeur du chien","Ce logiciel identifie les aboiements"] },
  { id: 346, wrong: ["Interdit de nager sans bonnet","Interdit de plonger tête la première","Interdit de nager trop vite","Interdit de rester plus d'1h","Interdit de toucher le fond"] },
  { id: 347, wrong: ["Un canard farci dans une oie","Un lapin farci dans un cochon","Un poulet farci dans un cochon de lait","Une pintade farcie dans un canard","Un faisan farci dans une dinde"] },
  { id: 348, wrong: ["Pour avoir critiqué le gouvernement","Pour avoir un tatouage visible","Pour avoir refusé de voter","Pour avoir porté un symbole étranger","Pour avoir chanté dans la rue"] },
  { id: 349, wrong: ["Il a été écrit en une seule nuit","Il a été lu par un président américain","Il a été brûlé puis réécrit de mémoire","Il a été volé et retrouvé 50 ans après","Il a inspiré 20 films différents"] },
  { id: 350, wrong: ["Il a plu des poissons du lac voisin","Il est tombé de la grêle rose","Il est tombé de la foudre en boule","Il a plu des grenouilles bleues","Il a neigé du sable du Sahara"] },
]

// Read the facts.js file
const factsPath = path.join(__dirname, '../src/data/facts.js')
let content = fs.readFileSync(factsPath, 'utf8')

// Build a map of updates by id
const updateMap = {}
UPDATES.forEach(u => { updateMap[u.id] = u })

// Parse and replace options in the file using regex per fact block
let updatedCount = 0
let skippedCount = 0

UPDATES.forEach(update => {
  const { id, wrong, correct } = update

  // Find the fact block by id
  // We'll use a regex to find options and correctIndex for this fact
  const idPattern = new RegExp(
    `(id:\\s*${id},[\\s\\S]*?options:\\s*)(\\[[\\s\\S]*?\\])(,[\\s\\S]*?correctIndex:\\s*)(\\d+)`,
    'g'
  )

  let matched = false
  content = content.replace(idPattern, (fullMatch, before, optionsStr, middle, oldCorrectIndex) => {
    matched = true

    // Extract the correct answer from the original options
    let originalOptions
    try {
      // Parse the options array - handle JS array syntax
      const cleanedOptions = optionsStr.replace(/,\s*\]/g, ']')
      originalOptions = JSON.parse(cleanedOptions)
    } catch(e) {
      // Try eval-like parsing for JS string literals
      try {
        originalOptions = eval(optionsStr)
      } catch(e2) {
        skippedCount++
        return fullMatch
      }
    }

    const correctAnswer = correct || originalOptions[parseInt(oldCorrectIndex)]

    // Build new options: [wrong1, wrong2, wrong3, wrong4, wrong5, correct]
    const newOptions = [...wrong, correctAnswer]
    const newCorrectIndex = 5

    const newOptionsStr = JSON.stringify(newOptions)
      .replace(/^\[/, '[')
      .replace(/\]$/, ']')

    updatedCount++
    return `${before}${newOptionsStr}${middle}${newCorrectIndex}`
  })

  if (!matched) {
    console.warn(`⚠️  No match found for fact id ${id}`)
    skippedCount++
  }
})

fs.writeFileSync(factsPath, content, 'utf8')
console.log(`✅ Updated ${updatedCount} facts`)
if (skippedCount > 0) console.log(`⚠️  Skipped ${skippedCount} facts (parse errors or not found)`)
